name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  publish-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      
      - name: Remove gemfile
        run: "[ -e Gemfile.lock ] && rm Gemfile.lock"
        
      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          username: ssrahul96
          password: ${{ secrets.GH_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository }}:1.0.${{ github.run_id }}
            ghcr.io/${{ github.repository }}:latest
